---
download_blockchain_db: true
network: "mainnet"

# Version, peer_count are in the network specific configs, so we can update testnet first
component: timelord
log_level: "INFO"
blockchain_backup_bucket: "{{ lookup('env', 'S3_BACKUP_BUCKET_NAME') }}"

# If set 'True', the timelord will create compact proofs of time, instead of
# extending the chain.
sanitizer_mode: True

# Number of VDF client processes to keep alive in the local machine.
process_count: 2

# 'send_uncompact_interval' seconds. Set to 0 if you don't use this feature. Recommended is 300
send_uncompact_interval: 300

# Prevent monit from being installed on the AMI
add_monit_config: true
