---
- hosts: all
  gather_facts: no
  roles:
    - name: wait-ssh

- name: Bluebox Base
  hosts: all
  become: yes
  roles:
    - name: unattended-upgrades #Waits for apt-update and apt-upgrade (if in progress), then removes unattended-upgrades (Security updates)
    - name: apt-update
    - name: git # Used for cloning the chia-blockchain git repository
    - name: python # Dependency for Chia-Blockchain
    - name: chia-blockchain # The chia-blockchain role contains custom variables, templates, and tasks for automating the installation and operation of Chia components
