---
- hosts: all
  gather_facts: no
  roles:
    - name: wait-ssh

- name: Bluebox Base
  hosts: all
  become: yes
  roles:
    - role: apt-update
    - role: unattended-upgrades
    - name: git
    - name: python
    - name: awscli
    - name: chia-blockchain
  tasks:
    - name: Reset cloud init
      ansible.builtin.shell: cloud-init clean --logs
