---
- hosts: all
  gather_facts: no
  roles:
    - name: wait-ssh

- name: Bluebox Base
  hosts: all
  become: yes
  roles:
    - name: unattended-upgrades
    - name: apt-update
    - name: git
    - name: python
    - name: chia-blockchain

