name: Generating the ap-southeast-1 bluebox image
on:
  workflow_dispatch:  # The workflow dispatch will allow for manual triggering of the workflow, either in GitHub or from another workflow
  push:
    branches: # When pushed to the main branch, the workflow with run
      - "main"
env:
  S3_BACKUP_BUCKET_NAME: ${{ secrets.S3_BACKUP_BUCKET_NAME }}
  S3_STATE_BUCKET_NAME: ${{ secrets.S3_STATE_BUCKET_NAME }}
  REGION: "ap-southeast-1"
jobs:
  packer_validate: # This will check the syntax for the packer file
    runs-on: [ k8s-public ] # k8s-public is used internally only. Recommend using ubuntu:latest in place of k8s-public
    container:
      image: alpine:latest
    timeout-minutes: 60
    steps:
      - name: install deps
        run: apk add aws-cli git packer ansible

      - uses: actions/checkout@v2

      - name: Checkout Roles
        uses: actions/checkout@v2
        with:
          repository: Chia-Network/ansible-roles
          path: ansible/roles

      - name: Packer Validate
        run: |
          packer validate bluebox-base-ap-southeast-1.json

  packer_build:
    needs: packer_validate
    runs-on: [ k8s-public ]
    container:
      image: alpine:latest
    timeout-minutes: 200
    steps:
      - name: Get ephemeral aws credentials
        uses: Chia-Network/actions/vault/aws-sts@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ secrets.VAULT_TOKEN }}
          role_name: ami-build

      - name: install deps
        run: apk add aws-cli git packer ansible

      - uses: actions/checkout@v2

      - name: Checkout Roles
        uses: actions/checkout@v2
        with:
          repository: Chia-Network/ansible-roles
          path: ansible/roles

      - name: Packer build
        run: |
          export AWS_POLL_DELAY_SECONDS=60 && export AWS_MAX_ATTEMPTS=180
          packer build bluebox-base-ap-southeast-1.json