name: Test Terraform/Plan
on:
  push:
    branches:
      - '**'
      - "!main"
concurrency:
  group: "main"
jobs:
  terraform_plan:
    runs-on: [k8s-public]
    container:
      image: hashicorp/terraform:latest
      options: --entrypoint /bin/sh
    steps:
      - uses: actions/checkout@v2
      - name: Get ephemeral aws credentials
        uses: Chia-Network/actions/vault/aws-sts@main
        with:
          vault_url: ${{ secrets.VAULT_URL }}
          vault_token: ${{ secrets.VAULT_TOKEN }}
          role_name: ami-build

      - uses: Chia-Network/actions/terraform/plan@main
        with:
          workspace: default
          varfile: /dev/null
          terraform_dir: terraform
